### PR TITLE
[RN Reloaded] Migrate web common/store and common/hooks to @audius/common

### PR DESCRIPTION
**Pull request by nicoback2**
### Description

Follow up PRs will be:
-Convert former JS files fully to TS
-The following files were copied over to @audius/common from web to ease the migration - need to reexamine and place exports where they belong (common or web)
-->services/nativeMobileInterface types
-->utils/reducer
-->utils/browserNotifications
-->utils/error
-Migrate files left behind in web/common/store in this PR to @audius/common

(but these can all be done after main reloaded work)

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-rest

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-rest

**Review by sliptype — APPROVED** [review]
🙌 🙌 🙌

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-rest

**Pull request merged**
