### PR TITLE
[C-2960][C-3069] Add transcode progress tracking for upload progress

### PR DESCRIPTION
**Pull request by amendelsohn**
### Description

> 🛑  Relies on https://github.com/AudiusProject/audius-protocol/pull/5941. Do not merge until libs update available 🛑 
> 🟢  Edit: (Merged and bumped sdk version)

- Upload progress now includes `transcode_progress` and artwork upload progress
	- Currently artwork is worth 10%, audio worth 90%
	- Within audio, file upload is worth 80% and transcode is worth 20%
	- These percentages can and maybe should be tweaked. For big files, transcode takes longer than upload. For small files, the reverse.

### Demo

https://www.loom.com/share/7374d336f1424c4fa8c2d55b0c48b984

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/amendel-transcode-progress

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/amendel-transcode-progress

**Comment by amendelsohn** [comment]
Migrated to https://github.com/AudiusProject/audius-protocol/pull/5950

**Pull request closed without merging**
