### PR TITLE
Fix optimizely for local dev

### PR DESCRIPTION
**Pull request by piazzatron**
### Description

Local dev should pickup staging optimizely config

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### CODE REVIEW

**Review by rickyrombo — APPROVED** [review]
Wow that's how easy this is?? My hero!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/piazz-local-dev-optimizely

**Review by dylanjeffers — APPROVED** [review]
yay finally!

**Comment by raymondjacobson** [comment]
merge?

**Pull request merged**
