### PR TITLE
[PLAT-1005] Parse for add track to playlist notification from backend

### PR DESCRIPTION
**Pull request by sabrina-kiam**
### Description
We never sent add track to playlist notifications from the backend, and never looked for it or mapped to it in the front end. This has been recently updated as part of plat-1005. This diff is updating the front end to map to this notification on reception

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

Ran locally against stage to confirm it works. I noticed there were some existing errors that were there before i made any changes but couldn't figure out how to address them.. seems to be working fine tho?

Screenshot 2023-05-25 at 4 33 25 PM

the notification:
Screenshot 2023-05-25 at 4 35 23 PM

### CODE REVIEW

**Review by dylanjeffers — APPROVED** [review]
wonderful!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-add-track-notif

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-add-track-notif

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-add-track-notif

**Pull request merged**
