### PR TITLE
[PAY-1212] [PAY-1146] Reactions and message UI polish

### PR DESCRIPTION
**Pull request by piazzatron**
### Description

https://github.com/AudiusProject/audius-client/assets/6780028/3e7dcaca-721f-41e2-9366-f77dd459fd3e

- Blocks reactions when your messages are blocked
- Also ensures that messages are no longer interactable at all when blocked (no hover states)
- Adds scale animation for reaction + button entrance
- Adds scale animation for reaction + button active state
- Adds opacity + shadow animations on bubble hover
- Changes the reaction popover border radius to match Figma
- 
Need to do a pass on mobile next
### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/pay-1212

**Review by rickyrombo — APPROVED** [review]

**Review by dharit-tan — APPROVED** [review]

**Comment by dharit-tan** [comment]
update mobile with new hook too plz!

**Comment by piazzatron** [comment]
> update mobile with new hook too plz!

will do

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/pay-1212

**Pull request merged**
