### PR TITLE
Update userbank function usage to pass config object

### PR DESCRIPTION
**Pull request by schottra**
### Description
Based on https://github.com/AudiusProject/audius-protocol/pull/5713
Updates our usage of those functions to pass a config object.

### Dragons
N/A

### How Has This Been Tested?
Locally verified

### How will this change be monitored?
N/A

### Feature Flags ###
N/A

### CODE REVIEW

**Review by rickyrombo — APPROVED** [review]
Looks good!

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/update-userbank-funcionts

**Pull request merged**
