### PR TITLE
[C-1092] Implement eager load utils in mobile

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

The rest of libs functionality should be able to use eager load utils now. Though, with tipping moved to AudiusAPIClient, there are only a few things.

https://www.youtube.com/watch?v=17KCHwOwgms

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

Local with simulator

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-c-1092

**Review by sliptype — APPROVED** [review]
Nice! I do think we could at least DRY up `parmsToQS` and `makeRequest` though right?

**Comment by raymondjacobson** [comment]
> Nice! I do think we could at least DRY up `parmsToQS` and `makeRequest` though right?

okayyyyy done. testing & will merge!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-c-1092

**Pull request merged**
