### PR TITLE
Fix associated wallets

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Add an online helper for users to connect wallets that got disconnected in Flare-101

This PR should be reverted after a sufficient amount of time has passed or all users have re-connected their wallets. (Since we have the user ids, the query is easy to run to check).

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

Tested on production account `rayjacobson`

The "migration" ran once for the user, fixed the wallets, and is not running again.

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-fix-disconnected-wallets

**Review by sliptype — APPROVED** [review]
Simple enough! Should we cherry pick onto the current release or the one going out Wednesday?

**Review by dylanjeffers — APPROVED** [review]
Looks great, do we have some logs around started, already has, completion, missing cid to make sure of anything?

**Comment by raymondjacobson** [comment]
> Simple enough! Should we cherry pick onto the current release or the one going out Wednesday?

probably both for web, can wait for mobile!

**Comment by raymondjacobson** [comment]
> Looks great, do we have some logs around started, already has, completion, missing cid to make sure of anything? 

I think the sql queries we have are sufficient to track progress, but i could add some new amplitude metrics if you're super into that? wdyt?

**Pull request merged**
