### PR TITLE
Make sure to read latest app build on desktop

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Fix desktop minor version updates.

Currently minor version updates will never go through because the build directory from an updated patch version will trump. This function (which @rickyrombo wrote) always picks the more recent build.

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

1. Cut staging release at 1.4.5
2. Added a build-staging with version 1.4.2 and made sure 1.4.5 was in /settings
3. Added a build-staging with version 1.4.6 and make sure 1.4.6 was in /settings

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Review by dylanjeffers — APPROVED** [review]
pray

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/raymondjacobson-patch-3

**Review by rickyrombo — COMMENTED** [review]
oh interesting - let me check my understanding:
- we were deleting the build dir on update
- we weren't copying the package.json to the build output
- we weren't checking the build dir when comparing versions for updates

**Comment by raymondjacobson** [comment]
> 

spot on

**Pull request merged**
