### PR TITLE
[CON-765] Default uploads to v2 and remove feature flag

### PR DESCRIPTION
**Pull request by theoilie**
### Description
Removes the `STORAGE_V2_TRACK_UPLOAD` feature flag and makes all consumers use the behavior for when the feature flag was `true`.

### How Has This Been Tested?
I'll test against staging after https://github.com/AudiusProject/audius-protocol/pull/5521 merges and this PR is updated to consume the latest libs/sdk version.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/theo-make-v2-upload-default

**Review by michellebrier — APPROVED** [review]
nice

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/theo-make-v2-upload-default

**Pull request merged**
