### PR TITLE
Fix playlist tile lint + bug

### PR DESCRIPTION
**Pull request by piazzatron**
### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Review by dylanjeffers — APPROVED** [review]
git hooks :D

**Comment by piazzatron** [comment]
> git hooks :D

were broken for me, somehow

**Comment by dylanjeffers** [comment]
> > git hooks :D
> 
> were broken for me, somehow

they actually dont do typecheck i dont think so not on you. looks like still has web-init issue?

**Review by sliptype — APPROVED** [review]

**Comment by piazzatron** [comment]
> > > git hooks :D
> > 
> > 
> > were broken for me, somehow
> 
> they actually dont do typecheck i dont think so not on you. looks like still has web-init issue?

yep i saw, fixed

**Pull request merged**
