### PR TITLE
Update react-scripts to 4.x.x to fix terser CI issues

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

I *think* per @piazzatron 's callout of this comment, updating react-scripts and the lot with the terser version change fixes our issues.
https://github.com/facebook/create-react-app/issues/8320#issuecomment-844314072

I've run this workflow thrice and it passed all builds each time (so 9 in total).

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

Upgrading the version here is always dangerous, so we should soak this on staging for as long as we can, etc.

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

* Ran locally
* Built locally
* Ran (and fixed) unit tests (jest version changed 2 majors)
* Ran (and updated) lint errors + configs (eslint/ts versions changed)

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://frontend-demo.audius.co/rj-terser-3

**Comment by raymondjacobson** [comment]
Closes https://linear.app/audius/issue/AUD-25/figure-out-terser-issues

**Review by jowlee — APPROVED** [review]
Played around with it and it seems fine.

**Review by sddioulde — APPROVED** [review]
Shukran!

**Pull request merged**
