### PR TITLE
Remove service selection modal

### PR DESCRIPTION
**Pull request by theoilie**
### Description
Removes modal used to select primary+secondaries. Also removes links to this modal from the settings page and track upload page (it previously displayed on track upload if the user doesn't have a replica set)

### Dragons
None

### How Has This Been Tested?
Signed up and uploaded locally. Made sure the text to get to the modal wasn't present on signup or in settings

### How will this change be monitored?
None

### Feature Flags ###
None

### CODE REVIEW

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/theo-remove-select-cn-modal

**Review by raymondjacobson — APPROVED** [review]
love a good negative diff. thank you!

**Comment by raymondjacobson** [comment]
I see that upload tests were already failing prior to this PR, but just FYI in case important.

**Comment by theoilie** [comment]
> I see that upload tests were already failing prior to this PR, but just FYI in case important.

thanks for flagging @raymondjacobson the video artifact shows heavy load pretty early in the cypress test for this PR and prior to this PR so I think this doesn't introduce a new issue

**Comment by dylanjeffers** [comment]
hey lets make sure we dont change all the locks on a change like this @raymondjacobson @theoilie

**Comment by theoilie** [comment]
@dylanjeffers sorry, I'm guessing the lockfile changes broke something? I can revert if needed

**Comment by dylanjeffers** [comment]
> @dylanjeffers sorry, I'm guessing the lockfile changes broke something? I can revert if needed

Not at all it's more an fyi, it's really a problem on our end that the locks for some reason aren't consistent for everyone. I handled in latest commit anyway

**Pull request merged**
