### PR TITLE
Polyfill BigInt

### PR DESCRIPTION
**Pull request by sliptype**
### Description

Attempt to fix crash on profiles with collectibles

Cannot repro locally at all, but can consistently repro on Stage and RC so going to merge and see if it fixes

Error being thrown: https://sentry.io/organizations/audius/issues/3834954449/?query=sdk.name%3Asentry.javascript.react-native+user%3A%22id%3A54432%22&referrer=issue-stream&sort=date&statsPeriod=14d

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Review by nicoback2 — APPROVED** [review]

**Review by dylanjeffers — APPROVED** [review]
Sweet let's see, was it cause of degubber that it's defined?

**Comment by sliptype** [comment]
> Sweet let's see, was it cause of degubber that it's defined?

`degubber` 😂

Even with it detached I was still not able to repro, pretty scary. Let's see if it fixes and then can dig into why we wouldn't be able to repro locally

**Comment by nicoback2** [comment]
> > Sweet let's see, was it cause of degubber that it's defined?
> 
> `degubber` 😂
> 
> Even with it detached I was still not able to repro, pretty scary. Let's see if it fixes and then can dig into why we wouldn't be able to repro locally

You should be able to repro using the "Release" configuration option! But even then I can only repro once and then have to rebuild it. It's really weird...

**Comment by sliptype** [comment]
> > > Sweet let's see, was it cause of degubber that it's defined?
> > 
> > 
> > `degubber` 😂
> > Even with it detached I was still not able to repro, pretty scary. Let's see if it fixes and then can dig into why we wouldn't be able to repro locally
> 
> You should be able to repro using the "Release" configuration option! But even then I can only repro once and then have to rebuild it. It's really weird...

I wasn't able to repro at all on ios, even with the release confg. BUT I can repro consistently on android device :) I'm working on a fix now

**Comment by nicoback2** [comment]
oooo

**Pull request merged**
