### PR TITLE
[pay-1214] add patch to fix inverted list ANR bug

### PR DESCRIPTION
**Pull request by schottra**
### Description
There appears to be an issue with Android 13 on some devices where react-native `FlatList` components can have performance issues or cause ANR screens. This is a temporary patch to use an alternate styling approach for inverted flatlists on Android until the issue is resolved.

See https://github.com/facebook/react-native/issues/30034 and https://github.com/facebook/react-native/issues/35350

### Dragons
I can't be sure this won't have any adverse effects on the chat list view. We don't use pull to refresh, so that won't be an issue. But we need to test this thoroughly on some non-Pixel Android devices

### How Has This Been Tested?
Tested locally on a Pixel 5

### How will this change be monitored?
N/A

### Feature Flags ###
N/A

### CODE REVIEW

**Review by rickyrombo — APPROVED** [review]
Haven't pulled and tested on device yet, but patch looks good to me

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Review by piazzatron — APPROVED** [review]
Code looks good, still need to test on physical device. Amazing find

**Review by piazzatron — APPROVED** [review]
Code looks good, still need to test on physical device. Amazing find

**Review by piazzatron — APPROVED** [review]
Code looks good, still need to test on physical device. Amazing find

**Review by dharit-tan — APPROVED** [review]

**Comment by dharit-tan** [comment]
Also pending test on device

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Pull request merged**
