### PR TITLE
Hide recaptcha always with custom render

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description
High level of confidence that this will make the captcha error message never show.
I believe the outer div is where the text got added -- effectively it replaced the contents of the outer div in this screenshot:
Screen Shot 2021-03-10 at 3 34 40 PM

Screen Shot 2021-03-10 at 3 52 15 PM

By choosing where to render recaptcha (inside of the ghost div, that should take care of things)

Screen Shot 2021-03-10 at 3 53 29 PM

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

touches index.html 

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

Against staging

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://frontend-demo.audius.co/rj-recaptcha-dom-fix

**Comment by vicky-g** [comment]
If im understanding this correctly, you
1. load the recaptcha render into the div with `id=recaptcha-hidden`
2. all the recaptcha stuff gets loaded into that element
3. that element is always hidden
4. so, effectively, anything recaptcha tries to append via their script gets hidden anyway

**Comment by raymondjacobson** [comment]
> If im understanding this correctly, you
> 
> 1. load the recaptcha render into the div with `id=recaptcha-hidden`
> 2. all the recaptcha stuff gets loaded into that element
> 3. that element is always hidden
> 4. so, effectively, anything recaptcha tries to append via their script gets hidden anyway

5. profit?

**Comment by vicky-g** [comment]
> > If im understanding this correctly, you
> > 
> > 1. load the recaptcha render into the div with `id=recaptcha-hidden`
> > 2. all the recaptcha stuff gets loaded into that element
> > 3. that element is always hidden
> > 4. so, effectively, anything recaptcha tries to append via their script gets hidden anyway
> 
> 1. profit?

### PROFITTTTTTTTTTTTTTTT 🤑

**Review by vicky-g — APPROVED** [review]
### 💰 💰 💰 💰 💰 💰 💰 💰 💰 💰 💰

**Pull request merged**
