### PR TITLE
[PAY-207] Refactor ArtistCard and fix usage in notifications

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

- Refactors ArtistCard to typescript following pattern in https://github.com/AudiusProject/audius-client/pull/1297
- Improves DynamicImage props to allow antd popover (used by ArtistPopover) to work with existing ProfilePicture component.

### How Has This Been Tested?

Verified styling and usage is the same across app instances

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-fix-artist-tile-popover

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-fix-artist-tile-popover

**Review by sddioulde — APPROVED** [review]
nice. looks good to me pending merge conflicts

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-fix-artist-tile-popover

**Pull request merged**
