### PR TITLE
NFT Playlists

### PR DESCRIPTION
**Pull request by dylanjeffers**
- Adds NFT Playlists
- Intergrates various fixes and features from release branch [release-5-19-22 ](https://github.com/AudiusProject/audius-client/tree/release-5-19-22) to main

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-nft-playlists

**Comment by sliptype** [comment]
I'm seeing the new styling for notifications on this branch:
image

Also the audio nft playlists seem to be broken

**Comment by dylanjeffers** [comment]
@sliptype talked with ray and we are looking to do new notifs for this release! Regarding nft stuff, happy to look into as well

**Review by sliptype — APPROVED** [review]
Thanks for getting this situated!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-nft-playlists

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-nft-playlists

**Pull request merged**
