### PR TITLE
Update plist to 1.1.66

### PR DESCRIPTION
**Pull request by rickyrombo**
### Description

Staging is stuck at 1.6.65 because this commit didn't make it back to main

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by dylanjeffers** [comment]
Are we trying to do full release again next week?

**Comment by rickyrombo** [comment]
1.6.66 is already out on production, staging isn't caught up since that commit was only on release

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Review by dylanjeffers — APPROVED** [review]
Thanks for context

**Comment by nicoback2** [comment]
yee @dylanjeffers staging testflight is stuck on 1.1.66 because version bump wasn't put on main first

**Comment by nicoback2** [comment]
ill put something in the docs about making sure to bump in main

**Pull request merged**
