### PR TITLE
Kj import stems into monorepo

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description

* Imported stems into the monorepo using lerna
* Update the readme to include the link to stems

### Dragons

This is a huge change, but it appears to have just ported all of the code over. Not sure if other changes need to be made in order to support the additional package so pls let me know if that is the case.

### How Has This Been Tested?

Imported, npm installed, build, typechecked, and ran storybook and it loaded fine 👍 

### How will this change be monitored?

N/A

### CODE REVIEW

**Review by nicoback2 — APPROVED** [review]
woooo! this LGTM but sebastian should prob take a look as well before merging

**Review by dylanjeffers — COMMENTED** [review]
Just wondering, was this able to be merged in preserving the commit history? i believe @sliptype is familiar with how to do that if not

**Review by sliptype — APPROVED** [review]
This all looks good to me! Yeah @dylanjeffers we used `npx lerna import --preserve-commit  ../stems`

**Comment by dylanjeffers** [comment]
So sweet nicee

**Pull request merged**
