### PR TITLE
[AUD-1602] Implement appearance setting

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

- Implements appearance setting
- Renames ThemeContextProvider to ThemeProvider
- Replaces `getTheme` with `theme`

### Dragons

- Had to move ThemeProvider inside the WebManager since we need the theme state from redux

- There is definitely some redundancy going on with how the theme is handled in the saga and being passed back down to the native app. Just to keep things consistent for now, I tried not to modify the existing logic and use of themeprovider.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-aud-1602-appearance-setting

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-aud-1602-appearance-setting

**Review by Kyle-Shanks — APPROVED** [review]
Clean, very nice

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-aud-1602-appearance-setting

**Pull request merged**
