### PR TITLE
[INF-180] Update client for new compose local dev

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Update client for new compose local dev setup. Removes configure local env script & .env.local env file. Also removes `cloud` command.

Congratulations! You've been tagged in this PR. To review this PR, please test this out!!

Instructions to get running

Running the protocol (checkout master):
```bash
# on remote
cd audius-protocol/dev-tools
bash setup.sh
audius-compose up
```

Running the client (checkout this branch):
```bash
# to run the client on your (mac) laptop
export AUDIUS_REMOTE_DEV_HOST=<ip>
networksetup -setautoproxyurl "Wi-Fi" "http://$AUDIUS_REMOTE_DEV_HOST:8080/proxy.pac"
npm run start:dev

# to run the client on your remote
npm run start:dev
# on your laptop (still required)
export AUDIUS_REMOTE_DEV_HOST=<ip>
ssh -N -L 3000:127.0.0.1:3000 -i ~/.ssh/google_compute_engine ubuntu@${AUDIUS_REMOTE_DEV_HOST}
```

On your laptop, URLs like this should resolve if you run the network setup proxy step.
http://audius-protocol-discovery-provider-1:5000/health_check

(README: https://github.com/AudiusProject/audius-protocol/tree/master/dev-tools)

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

This intentionally breaks running the client against `A up`
We gotta move on! There are some things still to add here, but for the most part things work well! (and are fast)

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

* Ran the stack
* Created account
* Uploaded track
* Did some other smoke testing

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-vss-new-setup

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-vss-new-setup

**Comment by cheran-senthil** [comment]
This now works with https://github.com/AudiusProject/audius-protocol/pull/3490 for account creation

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-vss-new-setup

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-vss-new-setup

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-vss-new-setup

**Review by cheran-senthil — APPROVED** [review]
I think my review is biased, however, I think this looks great and is great to merge now!

**Review by jonaylor89 — APPROVED** [review]
🥳🥳

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-vss-new-setup

**Pull request merged**
