### PR TITLE
[C-377] Replace antd popover with popup from stems

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description
[C-377]

Removed antd popover and used Popup component from stems
Slight change in positioning from positioned to the right to in the center above the anchor element

Screen Shot 2022-05-04 at 5 55 18 PM

### Dragons

N/a

### How Has This Been Tested?

Manually tested

### How will this change be monitored?

N/A

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Remove-antd-popover

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Remove-antd-popover

**Review by sliptype — APPROVED** [review]
code looks good! But we should probably check with Julian about the positioning

**Comment by Kyle-Shanks** [comment]
> code looks good! But we should probably check with Julian about the positioning

Checked in with Julian. All good 👍 
Also enjoy your time off dude!

**Pull request merged**
