### PR TITLE
[CON-765] Default v2 signup and fix local EM

### PR DESCRIPTION
**Pull request by theoilie**
### Description
- Removes v1 signup and only does v2
- Fixes EntityManager contract address on local dev
- Updates params passed to sanity checks to match recent sdk change
- ~TODO: Bump consumed sdk version once corresponding protocol PR is merged and sdk auto-deploys~

### How Has This Been Tested?
Signing up a user through the client with audius-compose no longer times out from polling Discovery due to using the wrong EntityManager address.

### Feature Flags ###
- Removes `STORAGE_V2_SIGNUP` and always uses the path where it was true
- Removes `WRITE_QUORUM_ENABLED`, which had been false for months

### CODE REVIEW

**Review by dylanjeffers — COMMENTED** [review]
awesome stuff

**Review by dylanjeffers — APPROVED** [review]

**Review by michellebrier — APPROVED** [review]
👍

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/theo-default-v2-everywhere

**Pull request merged**
