### PR TITLE
Move Lineup and Track page slices into common

### PR DESCRIPTION
**Pull request by sliptype**
### Description

This PR:
* Relocates the lineup slice and track page slice into `/common` in preparation for building out the RN track page and Lineup component

We will still need to move the corresponding sagas after the backend services have been migrated to common

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

### How Has This Been Tested?

Tested that things still compile and critical track page features work

### How will this change be monitored?

For features that are critical or could fail silently please describe the monitoring/alerting being added.

### CODE REVIEW

**Comment by sliptype** [comment]
> [AUD-1161 Track Tile](https://linear.app/audius/issue/AUD-1161/track-tile)

Oops, wrong branch name

**Review by rickyrombo — APPROVED** [review]
:rocket:

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-aud-1161-lineup

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-aud-1161-lineup

**Pull request merged**
