### PR TITLE
[C-2316] Add remote config for all oauth verification

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

* Remove compete profile w/ tiktok and make remote config variables that follow the existing instagram ones
* Add twitter remote config to match

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

Created vars in optimizely and played with a bunch of pages (web & mobile) against staging.

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by raymondjacobson** [comment]
I ran lint:fix at root and got some common changes. Hope that's ok!

**Review by sliptype — APPROVED** [review]
lgtm! but what is the benefit of doing remote config flags over feature flags? Do we have a limit on number of features?

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-c-2316

**Comment by raymondjacobson** [comment]
> lgtm! but what is the benefit of doing remote config flags over feature flags? Do we have a limit on number of features?

Honestly none other than it's what we decided on as our convention when we first added these. Remote config = always on/permanent config vs. feature flags to control % rollout. I'm down to change the rules if we want!

The amount of JSON is basically equivalent:
```
{
                    "defaultValue": "true",
                    "type": "boolean",
                    "id": "20072260176",
                    "key": "DISPLAY_INSTAGRAM_VERIFICATION_WEB_AND_DESKTOP"
                },
```


```
{
            "experimentIds": [],
            "rolloutId": "23637840558",
            "variables": [],
            "id": "23648700429",
            "key": "DISPLAY_INSTAGRAM_VERIFICATION_WEB_AND_DESKTOP"
        }
        ```

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-c-2316

**Pull request merged**
