### PR TITLE
[C-403] Fix lineup with artist pick

### PR DESCRIPTION
**Pull request by sliptype**
### Description

* Instead of slicing the artist pick out of the response, set it to null and keep track of the null count to avoid messing up the offset

### Dragons

This could break lineups

### How Has This Been Tested?

Locally against prod, web and ios

### How will this change be monitored?

Michael will confirm fix

### CODE REVIEW

**Review by jowlee — APPROVED** [review]
lgtm

**Comment by jowlee** [comment]
would also like to check that the lineup ends and doesn't try to load forever

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-fix-profile-lineup

**Comment by sliptype** [comment]
> would also like to check that the lineup ends and doesn't try to load forever

Good call, there was some weird infinite load behavior at the end of the lineup. I ended up fixing the problem in a different way, it's not very elegant but  I didn't want to use `containsDeleted` because we are no longer using it anywhere else and updated our endpoints to account for deleted items. 

Essentially needed to keep track of "deleted" and "removed because of artist pick" separately, I did this by setting the artist pick item as null and keeping track of a `nullCount`. This fixes on both web and mobile

**Review by dylanjeffers — APPROVED** [review]
tricky for sure! makes sense though

**Pull request merged**
