### PR TITLE
[PAY-1606] Updates gated content experience 

### PR DESCRIPTION
**Pull request by schottra**
### Description
This is a feature branch containing an updated experience for gated content in anticipation of the upcoming USDC implementation. Track tiles and track details pages have received visual overhauls, and USDC variants have been added behind feature flags. Remaining USDC work will be done iteratively behind the flag.

All code in this branch has been previously reviewed as part of incremental PRs. Check the commit list for more information.

### Dragons
It's a big change that should be cosmetic. But there is always some risk with this much code. We can revert if any major issues pop up.

### How Has This Been Tested?
Each PR has been tested locally against desktop, mobile web, and native mobile.

### How will this change be monitored?
We will be doing a QA pass on staging to verify. Will revert the PR if any major issues pop up.

### Feature Flags ###
All USDC-related features are behind a feature flag that is off by default in production.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/gated-content-updates

**Review by dharit-tan — APPROVED** [review]
approving this so we can merge for testing.
Also, should we not squash these commits?

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/gated-content-updates

**Comment by schottra** [comment]
> #### ⚠️ GitGuardian has uncovered 1 secret following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secret in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

Discussed this offline. It's a false alarm generated by a whitespace change on main in a file that exports constants which _appear_ to be secrets.

**Pull request merged**
