### PR TITLE
[C-1295] Update new tables to allow drag to add to playlist

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description
Quick updates to allow tracks within new tables to be able to be dragged into playlists in the side nav

### Dragons

N/A

### How Has This Been Tested?

Manually tested

### How will this change be monitored?

N/A

### Feature Flags ###

N/A

### CODE REVIEW

**Review by dylanjeffers — COMMENTED** [review]
Knowing nothing, is it stable to use index for drag-drop vs something like a key/id?

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Update-new-tables-to-allow-drag-track-to-playlist

**Comment by Kyle-Shanks** [comment]
> Knowing nothing, is it stable to use index for drag-drop vs something like a key/id?

Good thought. The index here is only being used in the new code that I added for the new tables and is only used for reorder logic, which has been stable so far for all of the testing. the track id will be used for the id prop and now matches the pattern that the other drag and drop components use around the app so this should work

**Review by dylanjeffers — APPROVED** [review]
makes sense!

**Pull request merged**
