### PR TITLE
Bump client version to 1.1

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description

Minor version bump

### CODE REVIEW

**Comment by sliptype** [comment]
We haven't really discussed this, but we should keep the package versions in sync using `npx lerna version patch`: https://github.com/lerna/lerna#fixedlocked-mode-default

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-bump-minor-to-1.1

**Comment by dylanjeffers** [comment]
just wondering, what would be the case of minor vs patch updates?

**Comment by raymondjacobson** [comment]
@sliptype  is this PR good to merge as is or will lerna do something different?

**Comment by sliptype** [comment]
@raymondjacobson Lerna would update the version in `lerna.json` and `mobile`, mainly important if we ever want to publish these packages. But it also makes sense to keep all the versions in sync if we want to name the release branch after that version IMO

**Pull request closed without merging**
