### PR TITLE
Move services from web/common to @audius/common

### PR DESCRIPTION
**Pull request by nicoback2**
### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Review by sliptype — APPROVED** [review]
Looks good to me!

It seems like we need to export `USER_ID_AVAILABLE_EVENT` from the remote config index too

**Review by dylanjeffers — APPROVED** [review]
killer job

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-hooks

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-hooks

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-hooks

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--web-common-hooks

**Pull request merged**
