### PR TITLE
[C-2792] Surface play count for hidden tracks

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Fixes issue where play count was not showing up for owners of hidden tracks.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-2792-fix-play-count

**Comment by sabrina-kiam** [comment]
just checking would track rows within a playlist be affected? prob not cuz i assume you can't add hidden tracks to a playlist ?  otherwise thanks for fixing!

**Review by sabrina-kiam — APPROVED** [review]

**Comment by dylanjeffers** [comment]
> just checking would track rows within a playlist be affected? prob not cuz i assume you can't add hidden tracks to a playlist ?  otherwise thanks for fixing!

Good looks will look into that. Should just be for a private playlist but I can see the arg

**Review by sabrina-kiam — COMMENTED** [review]
legend

**Pull request merged**
