### PR TITLE
Switch back to audius RPC endpoint for stage

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description
https://poa-gateway.staging.audius.co/ is healthy again and much more performant than the public sokol RPC endpoint.

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

n/a just staging env

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

Locally against stage
1. Reposted track while pointed at a discovery node & identity also on our RPC
2. Uploaded a track while pointed at creator node, discovery node & identity also on our RPC

### CODE REVIEW

**Comment by hareeshnagaraj** [comment]
looks great! will let @sliptype approve

**Review by sliptype — APPROVED** [review]
In prod we have a fallback RPC endpoint, but I guess we don't really need one for stage

Looks good!

**Comment by raymondjacobson** [comment]
> In prod we have a fallback RPC endpoint, but I guess we don't really need one for stage
> 
> Looks good!

No harm in having it & probably good to be consistent w/ prod. I'll add the fallback!

**Comment by audius-infra** [comment]
Preview this change https://frontend-demo.audius.co/rj-repoint-poa-gateway

**Pull request merged**
