### PR TITLE
Fix sign on redirect for existing users on native mobile

### PR DESCRIPTION
**Pull request by sliptype**
### Description

Fixes a bug on native mobile where following a "sign up" link from web with the app already logged in in the background causes a blank screen.

`SignOnProvider` was handling the redirect from `signon` to `trending` for already sign in users, but on native mobile `SignOnProvider` was never rendered. Moving the redirect to the top level `SignOn` component fixes the issue

### Dragons

This moves the referrer logic up one level, @rickyrombo is there anything to be worried about here?

### How Has This Been Tested?

iOS simulator

### How will this change be monitored?

For features that are critical or could fail silently please describe the monitoring/alerting being added.

### CODE REVIEW

**Review by rickyrombo — APPROVED** [review]
Looks good to me - seems like this would also fix retroactive referrals for existing users that tried to get referred via mobile. A two-fer!

EDIT: Native mobile previously depended on
https://github.com/AudiusProject/audius-client/blob/d71a8f8d94e9244cda5a99926be50ed3ba3620c2/packages/mobile/src/components/signon/SignOn.tsx#L424-L446

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-fix-sign-on-redirect

**Review by dylanjeffers — APPROVED** [review]
great fix, so quick!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-fix-sign-on-redirect

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-fix-sign-on-redirect

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-fix-sign-on-redirect

**Pull request merged**
