### PR TITLE
[AUD-1428] Upgrade antd

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Upgrades antd dependency to next major version, which includes a massive bundle-size improvement (they now properly tree-shake their icons)

Before:
@ant-design
+ 
(concaten

After: 
antd

### Dragons

There were slight core styling changes, so we should do a smoke test the components that use ant

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-upgrade-ant

**Comment by raymondjacobson** [comment]
We should not merge this PR. we've tried before and it broke a TON of UI. We should be removing usage of it (already on the roadmap).

**Comment by dylanjeffers** [comment]
> We should not merge this PR. we've tried before and it broke a TON of UI. We should be removing usage of it (already on the roadmap).

Sounds good to me! fwiw from the little smoke testing i was doing things seemed more-or-less okay!

**Comment by sliptype** [comment]
One of the main things we use antd for is tables. This branch is crashing for me on any page with a table like Favorites, Artist Dashboard, playlists

**Comment by dylanjeffers** [comment]
Ahh I see, will give it a quick once over to see if it's an easy fix

**Pull request closed without merging**
