### PR TITLE
[C-1887 C-1888] Improve profile and explore screen performance

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

- Improves profile collections performance by waiting to load user's albums/playlists until navigating to tab
- Improves explore performance by waiting to fetch featured playlists/artists until user navigates to tab

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-1888-collections-performance

**Review by Kyle-Shanks — APPROVED** [review]
Clean stuff 👍

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-1888-collections-performance

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-1888-collections-performance

**Pull request merged**
