### PR TITLE
Add Dapp store publishing in CI

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Add CI for solana saga dapp store release

All release branches will have a mobile hold step for solana phone push

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

Could accidentally publish solana build? 🤷 

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

Didn't want to run and full test and deploy until we were actually ready, but it got quite far on the last run
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/15288/workflows/8d320d67-55c2-4072-b63b-26e059076bf3/jobs/143269

and the only change at that point was just to make sure we used node 18 via nvm use in the dapp store CI commands. have confirmed that the solana key gets loaded correctly

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

CI

### CODE REVIEW

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-dapp-store-ci

**Review by sliptype — APPROVED** [review]
Let's go! Amazing

**Review by dylanjeffers — CHANGES_REQUESTED** [review]
Looks great, guessing we don't need the lock change?

**Comment by raymondjacobson** [comment]
> Looks great, guessing we don't need the lock change?

Needed b/c of latest pnpm

**Pull request merged**
