### PR TITLE
Use stems for modals everywhere!

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Trello Card Link
https://trello.com/c/A92WGnVo/1686-consolidate-audiusmodal

### Description
Uses stems modal for all modals (depends on new release to be cut from stems)

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?
All the modals!

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

Replaced each modal 1 by 1 and compared to existing staging. Some subtle diffs (like 0.6 opacity vs. antd's 0.66, etc.), but overall great! See changes in stems PR https://github.com/AudiusProject/stems/pull/26

Review on ray.audius.co

### CODE REVIEW

**Comment by piazzatron** [comment]
Found an issue looking at advanced track edits on small screens:

**Comment by piazzatron** [comment]
Source Files upload on an existing track is broken now (if you click the part of the modal that's supposed to direct you to browse)

**Comment by raymondjacobson** [comment]
> Source Files upload on an existing track is broken now (if you click the part of the modal that's supposed to direct you to browse)
> 
> Looks to be the same issue with Remix modals

Fixed in stems

**Comment by raymondjacobson** [comment]
> Found an issue looking at advanced track edits on small screens:

This img seems to be broken. was the issue that it was just not popping up? i wonder if we have the same issue on prod b/c it has a large width specified

**Comment by raymondjacobson** [comment]
> > Found an issue looking at advanced track edits on small screens:
> 
> This img seems to be broken. was the issue that it was just not popping up? i wonder if we have the same issue on prod b/c it has a large width specified

NVM, found what you meant

**Comment by audius-infra** [comment]
Preview this change https://frontend-demo.audius.co/rj-modals

**Comment by piazzatron** [comment]
Found one more bug - it looks like if you edit track -> download + source files -> close download + source files, it dismisses the edit track modal as well

**Comment by piazzatron** [comment]
search seems broken on FE demo - not sure if related to this branch, but worth a look. enter some text into the input and press enter - I see `Sorry, we couldn't find anything that matches ""`

**Review by piazzatron — APPROVED** [review]
Looks great aside from the two things mentioned above!

**Comment by raymondjacobson** [comment]
> Found one more bug - it looks like if you edit track -> download + source files -> close download + source files, it dismisses the edit track modal as well.
> 
> edit: looks like the same issue w the edit -> remix flow
> 
> edit2: looks like a consistent bug with multiple modals + dismissing the most recent one. I see the same thing with edit playlist -> delete -> close delete modal

Ah, nice. fixed this with click outside, but not the dismiss button I guess because that's a click inside maybe?

**Pull request merged**
