### PR TITLE
[C-1267] Fingerprint in react-native

### PR DESCRIPTION
**Pull request by sliptype**
### Description

~This doesn't 100% work because the `2.0.0` release of https://github.com/fingerprintjs/fingerprintjs-pro-react-native doesn't support our version of react-native. The previous version `1.0.4` doesn't support passing the `linkedId` that we use to match fingerprints with user handles

It's not really feasible to upgrade react native before releasing the reloaded work. Wanted to get some input on whether this react-native fingerprint without `linkedId` would be fine for now. I assume we are using that to prevent extra fingerprints on the same user?~

Works after removing `__apply_Xcode_12_5_M1_post_install_workaround` script from our podfile. I don't believe this script is necessary anymore.

* Add react-native Fingerprint client

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Review by dylanjeffers — COMMENTED** [review]
Code wise looks good, but yeah lets see what piazza thinks. So is there a minimum for v2, is it 7.0.1 requirement? kinda wild, is there a specific react-native feature that's needed there or something?

**Comment by sliptype** [comment]
> Code wise looks good, but yeah lets see what piazza thinks. So is there a minimum for v2, is it 7.0.1 requirement? kinda wild, is there a specific react-native feature that's needed there or something?

@dylanjeffers So i'm not sure exactly why it doesn't work but i was getting an error similar to this https://github.com/stripe/stripe-react-native/issues/970

Our deployment target is already 12.0 so the error didn't make much sense but other people were able to fix it by upgrading react-native. I did try upping the deplyoment target to no avail

**Comment by dylanjeffers** [comment]
> > Code wise looks good, but yeah lets see what piazza thinks. So is there a minimum for v2, is it 7.0.1 requirement? kinda wild, is there a specific react-native feature that's needed there or something?
> 
> 
> 
> @dylanjeffers So i'm not sure exactly why it doesn't work but i was getting an error similar to this https://github.com/stripe/stripe-react-native/issues/970
> 
> 
> 
> Our deployment target is already 12.0 so the error didn't make much sense but other people were able to fix it by upgrading react-native. I did try upping the deplyoment target to no avail

Gotcha, yeah in that thread some folks were saying cache stuff, and then another mentioned an m1 workaround potentially, dunno

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-c-1267-react-native-fingerprint

**Comment by sliptype** [comment]
> > > Code wise looks good, but yeah lets see what piazza thinks. So is there a minimum for v2, is it 7.0.1 requirement? kinda wild, is there a specific react-native feature that's needed there or something?
> > 
> > 
> > @dylanjeffers So i'm not sure exactly why it doesn't work but i was getting an error similar to this [stripe/stripe-react-native#970](https://github.com/stripe/stripe-react-native/issues/970)
> > Our deployment target is already 12.0 so the error didn't make much sense but other people were able to fix it by upgrading react-native. I did try upping the deplyoment target to no avail
> 
> Gotcha, yeah in that thread some folks were saying cache stuff, and then another mentioned an m1 workaround potentially, dunno

Oh yup, I actually was able to fix it by removing that `__apply_Xcode_12_5_M1_post_install_workaround` script which I don't believe is necessary anymore since we upgraded react-native previously and are on newer versions of xcode now

**Comment by dylanjeffers** [comment]
Hells yes!

**Review by dylanjeffers — APPROVED** [review]
Money

**Pull request merged**
