### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by sliptype**
### Description

[f81ac4c7a] [Pay-516] Show see more only if profile header should be expansible on mobile. (#1721) Saliou Diallo
[1a98edb92] [C-843] Native analytics sagas (#1734) Sebastian Klingler
[447d44f7a] [PAY-531] Fix become first supporter bug (#1735) Saliou Diallo
[26635fae6] [C-857] Add cache and confirmer to mobile sagas (#1738) Dylan Jeffers
[671cac1d6] Fix eager discovery loader (#1737) Raymond Jacobson
[d6bbbdd38] [C-856] Use solanaweb3 in native, improve account flow (#1736) Dylan Jeffers
[371dcdd6f] [C-745, C-746, C-747, C-748, C-750, C-752, C-811, C-812] New Tables (#1700) Kyle Shanks
[2d4983075] [C-830] Move account to common store and set up with sign in (#1733) Raymond Jacobson
[677e3a070] [PAY-497] Fix native mobile install challenge (#1729) Michael Piazza
[3f8b53a81] [PAY-545] [PAY-542] Buy $AUDIO tile on $AUDIO page (#1667) Marcus Pasell
[80b78092b] Fix no-undef, add rule back to eslint-config (#1732) Dylan Jeffers
[afe241e9a] [C-842] Add scrypt and account sagas to mobile (#1730) Raymond Jacobson
[8a98d8bae] [PAY-536] Short-circuits reward claim retries on AAO error (#1724) Reed
[97a108704] [C-841] Put getFeatureEnabled in storeContext (#1727) Sebastian Klingler
[f5daf2bc0] [C-832] Add local-storage service to saga context (#1718) Dylan Jeffers
[49597dff3] [PAY-537] Adds new AAO error code emojis (#1728) Reed
[59094b36e] Fix wallet-client usages (#1726) Dylan Jeffers
[5767e78af] Re-add native store context to fix optimizely import resolution (#1725) Dylan Jeffers
[8e753697d] Remove common sagas from native (#1723) Dylan Jeffers
[7e4011736] Fix missing audiusBackendInstance in search-bar saga (#1722) Dylan Jeffers
[e215be36f] [C-815] Fix electron update (#1717) Sebastian Klingler
[ad8ef4138] Don't use yield * because not using typed-redux-saga in this file (#1716) Sebastian Klingler
[44108bb8f] [C-786] Fix width of foreground hero image (#1709) Raymond Jacobson
[594588264] [C-608] Fix tooltip bugs (#1701) Raymond Jacobson
[bb8f92477] fix: upgrade glsl-random from 0.0.4 to 0.0.5 (#1680) Dheeraj Manjunath
[292ef96c6] fix: upgrade deepcopy from 0.3.3 to 0.6.3 (#1679) Dheeraj Manjunath
[df1e82299] fix: upgrade @cloudflare/kv-asset-handler from 0.0.11 to 0.2.0 (#1678) Dheeraj Manjunath
[b1c1ebccd] [C-768] Fix toast on no artwork (#1702) Raymond Jacobson
[7e7f6eb8e] [PAY-529] Add native dethroned notification (#1714) Dylan Jeffers
[19d2ccb86] Fix typecheck with updated sdk version (#1715) Dylan Jeffers

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-version-bump-1.3.0

**Comment by sliptype** [comment]
Seeing a very strange error on ios and android builds: 
```
Error: Unexpected token name «n», expected punc «,» in file node_modules/@solana/web3.js/lib/index.native.js at 4240:32
    at minifyCode (/Users/distiller/audius-client/packages/mobile/node_modules/metro-transform-worker/src/index.js:99:13)
    at transformJS (/Users/distiller/audius-client/packages/mobile/node_modules/metro-transform-worker/src/index.js:317:28)
    at transformJSWithBabel (/Users/distiller/audius-client/packages/mobile/node_modules/metro-transform-worker/src/index.js:408:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/distiller/audius-client/packages/mobile/node_modules/metro-transform-worker/src/index.js:569:12)
    ```

**Comment by dylanjeffers** [comment]
> 

ah yeah... hmm i think that is due to a change i made in libs, lets huddle

**Review by dylanjeffers — APPROVED** [review]
nicee

**Pull request merged**
