### PR TITLE
Redirect to signup if auth rate limit error

### PR DESCRIPTION
**Pull request by sddioulde**
### Description

Redirect to signup and show try again toast if auth rate limit error.

### Dragons

Make sure handle error logic that reports/redirects/etc. isn't broken for other paths.

### How Has This Been Tested?

Manual client test

### How will this change be monitored?

Is it worth reporting to Sentry but not paging or tweaking the alert trigger somehow?
Or reporting a diff erro type to sentry that does not page? @raymondjacobson

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-auth-rate-limit

**Review by raymondjacobson — APPROVED** [review]

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-auth-rate-limit

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-auth-rate-limit

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-auth-rate-limit

**Pull request merged**
