### PR TITLE
[C-2812] Use storageNodeSelector in libs, fix mobile images

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Uses latest sdk to leverage exported StorageNodeSelector in libs and sdk.
Uses this to fix mobile image fetches for v2 users

### CODE REVIEW

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Review by rickyrombo — APPROVED** [review]
Looks great to me. Super minor nit, but maybe we should put our SDK singleton services under a nested `sdk` directory in services? I have a feeling we're going to make al ot of these 😢

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Review by theoilie — APPROVED** [review]
many thanks!!

**Comment by rickyrombo** [comment]
> > Looks great to me. Super minor nit, but maybe we should put our SDK singleton services under a nested `sdk` directory in services? I have a feeling we're going to make a lot of these 😢
> 
> Super down! though since its also used in libs, its kinda like a general service?

Yeah, they're still SDK services though (they come from SDK), they're just being used in libs right? Either way, it's super minor nit

**Review by sliptype — APPROVED** [review]

**Comment by dylanjeffers** [comment]
> > > Looks great to me. Super minor nit, but maybe we should put our SDK singleton services under a nested `sdk` directory in services? I have a feeling we're going to make a lot of these 😢
> > 
> > 
> > Super down! though since its also used in libs, its kinda like a general service?
> 
> Yeah, they're still SDK services though (they come from SDK), they're just being used in libs right? Either way, it's super minor nit

oh yeah totally! updated

**Pull request merged**
