### PR TITLE
[INF-445] Upgrade client to node 18, npm 9, and npm workspaces

### PR DESCRIPTION
**Pull request by sliptype**
### Description

More details on using getting started with node 18 and npm 9 here https://www.notion.so/audiusproject/Getting-Started-with-Node-18-and-npm-workspaces-39790b3a5f2c44379ffbef956f291102

* Set node version in `.nvmrc` - this will force people to use node 18.17 via the preinstall script
* Configure npm workspaces
  * There is now a single package-lock.json at root
  * Remove local dependencies from relevant package.jsons, they will be resolved automatically by npm
* Remove lerna and replace with npm commands
* Add `legacy-peer-deps=true` to `.npmrc`. npm 9 enforces strict peer deps and our depedency tree violates it in a multitude of ways. Until we fix all peer dependency versions, legacy-peer-deps is required
* Remove `npm-force-resolutions` in favor of npm overrides
* Support nested patch-package by running patch-package from root
* Update readme to remove references to lerna
* Upgrade sentry

#### Web
* Update webpack paths to resolve deps from root
* Expose `process` and `Buffer` on window manually because webpack ProvidePlugin isn't able to resolve modules from the root (even when fully specifying the path)

#### Mobile
* Update all paths to resolve deps from root
* Update readme to include requirement of starting metro server before running app

#### CI
* Upgrade node images to `cimg/node:18.17`
* Remove `create_concatenated_package_lock`, no longer needed bc there is a single package-lock

### Dragons

Lots of package-lock changes! Will want thorough testing. Also potential that new npm workflows break on CI

### How Has This Been Tested?
Everything builds

Tested critical paths on web, ios, and android

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Review by dylanjeffers — APPROVED** [review]
Ran through everything and confirmed everything is working on developer side. Incredible job 🔥

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-inf-445-upgrade-client-node-18-workspaces

**Pull request merged**
