### PR TITLE
[CON-111] check is_available flag

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Checks the is_available flag in addition to _blocked for content availability on the client.

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

Waiting to test against stage

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

Available content in production. Possible to instrument some addl amplitude charts, but probably not warranted at this time.

### CODE REVIEW

**Review by vicky-g — APPROVED** [review]
amaze

**Comment by vicky-g** [comment]
lets hold off on merge until con-112 is tested on staging!

**Comment by vicky-g** [comment]
con-112 is tested and working on stage. we can probably merge this now? @raymondjacobson

**Comment by raymondjacobson** [comment]
> con-112 is tested and working on stage. we can probably merge this now? @raymondjacobson 

did we test it locally pointed at stage?

**Pull request merged**
