### PR TITLE
[C-363] Remove antd progress component and use stems ProgressBar component

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description

[C-363]

* Replace antd progress component with stems progress component
* Delete unused ProgressBar component

### Dragons

Does not have the active flashing animation, but can be added if the stems component is updated

### How Has This Been Tested?

Manually tested

### How will this change be monitored?

N/A

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Remove-antd-progress-component

**Review by sliptype — APPROVED** [review]
I guess we are losing the error state here but that's probably fine

**Comment by Kyle-Shanks** [comment]
> I guess we are losing the error state here but that's probably fine

Yea, for now. It should still have copy letting the user know that an error happened and we can update the ProgressBar component in stems to handle more states if need be

**Comment by raymondjacobson** [comment]
Wait, why are we removing the error state? did we check in w/ julian? we should avoid changing UI with this migration

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Remove-antd-progress-component

**Pull request merged**
