### PR TITLE
[AUD-83] Fix linux builds and rename desktop "bounce" app to "staging"

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Fix linux builds & rename staging desktop app from "bounce" to "staging"
Bounce was a cool name, but is just extra misdirection...

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

On CI: https://app.circleci.com/pipelines/github/AudiusProject/audius-client/3502/workflows/f13b678d-daf6-41d9-bfe2-04934cf94cd8

### How will this change be monitored?

For features that are critical or could fail silently please describe the monitoring/alerting being added.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-rename-bounce-staging

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-rename-bounce-staging

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-rename-bounce-staging

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-rename-bounce-staging

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-rename-bounce-staging

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-rename-bounce-staging

**Comment by raymondjacobson** [comment]
Subsequent PR to address https://linear.app/audius/issue/AUD-1433/staging-and-prod-desktop-environments-clash-on-local-storage

**Review by sliptype — APPROVED** [review]
Nice! Is the plan to rename the mobile app too?

**Comment by raymondjacobson** [comment]
> Nice! Is the plan to rename the mobile app too?

yes we definitely should. just more of a PITA :) i can take on that work

**Pull request merged**
