### PR TITLE
[C-705] Fix mac desktop build

### PR DESCRIPTION
**Pull request by sliptype**
### Description

Installs `dmg-license` on the fly because it is an optional dependency due to only being installable on mac. I didn't want to prevent devs from using non mac systems, hence installing the package in ci

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Review by dylanjeffers — APPROVED** [review]
awesome makes sense, so installing it fails in windows and linux? or just a way to prevent node_modules from getting to large? only thought is that if it is kinda large, might be faster to just include in node_mods and rely on our caching?

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sk-c-705-fix-mac-desktop-build

**Comment by sliptype** [comment]
> awesome makes sense, so installing it fails in windows and linux? or just a way to prevent node_modules from getting to large? only thought is that if it is kinda large, might be faster to just include in node_mods and rely on our caching?

According to this thread it fails on other platforms: https://github.com/electron-userland/electron-builder/issues/6489

But also I don't think we are specifying `--no-optional` anywhere so not sure why it isn't installed, maybe a lerna thing?

**Comment by dylanjeffers** [comment]
> > awesome makes sense, so installing it fails in windows and linux? or just a way to prevent node_modules from getting to large? only thought is that if it is kinda large, might be faster to just include in node_mods and rely on our caching?
> 
> According to this thread it fails on other platforms: [electron-userland/electron-builder#6489](https://github.com/electron-userland/electron-builder/issues/6489)
> 
> But also I don't think we are specifying `--no-optional` anywhere so not sure why it isn't installed, maybe a lerna thing?

word, weird, well good fix

**Pull request merged**
