### PR TITLE
Add error message helper

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Adds error message helper, which gracefully handles extracting error message from catch block error.
Fixes one of our many error cases

Note, this will be useful for the incoming typescript upgrade from v3 to v4 in web.

Information about the type situation, and inspiration for helper: 
https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript

### CODE REVIEW

**Review by sliptype — APPROVED** [review]
Awesome! I wonder what portion of our TS v4 errors are this issue

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-add-error-message-helper

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-add-error-message-helper

**Comment by dylanjeffers** [comment]
> Awesome! I wonder what portion of our TS v4 errors are this issue

I checked and in the sagas there are quite a few, and in fact we are mostly doing as Error casts in other cases so will address those as well

**Pull request merged**
