### PR TITLE
Remove write_metadata_through_chain flag

### PR DESCRIPTION
**Pull request by michellebrier**
### Description
TODO merge [libs](https://github.com/AudiusProject/audius-protocol/pull/5293) changes first and bump SDK dependency here.

DO NOT MERGE until flag has been on in prod for a while and we are confident everything is working appropriately.

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###
Removes `write_metadata_through_chain`

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mbrier/con-712/remove-metadata-write-flag

**Review by dylanjeffers — APPROVED** [review]
looks great, love how this is setup ready to go ahead of time

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mbrier/con-712/remove-metadata-write-flag

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Pull request merged**
