### PR TITLE
[PAY-923] DMs: Add desktop entrypoints

### PR DESCRIPTION
**Pull request by rickyrombo**
### Description

- Converts `StatBanner` to TypeScript and refactors it, removing unused props and simplifying button logic and styles
- Adds new `Alignment` prop to `Popup`, allowing it to be placed not just kitty-corner, but also like a proper dropdown: 
image
- Adds UI to the user profile for messaging users (behind CHAT_ENABLED)
- Adds item to the nav popup menu to get to the chats screen (behind CHAT_ENABLED)

Out of scope/Todos:
- Implementing blocking/unblocking menu option
- Checking if a user can be messaged before showing the message UI
- Loading state for when message is clicked
- Do the right thing for users not logged in
- New message indicator

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

- Make sure this works the same when the feature flag is off

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

- Tested Desktop Web on Chrome against staging data

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

N/A

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

New StatsBanner w/ Messages, Dropdown behind CHATS_ENABLED

### CODE REVIEW

**Comment by rickyrombo** [comment]
Feel free to review the full PR, but I added:
- @Kyle-Shanks to review Stems changes
- @dylanjeffers to review web UI changes
- @raymondjacobson for context on StatBanner stuff to ensure I'm not missing something with the refactor

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-dms-profile

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-dms-profile

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-dms-profile

**Review by dylanjeffers — APPROVED** [review]
nice updates, especially on popover!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-dms-profile

**Pull request merged**
