### PR TITLE
Fix @audius/common external warnings, model imports, lint

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Adds a few random fixes i noticed while integrating with new common!

- Fixes remaining common external warnings
- Removes /index imports
- Uses absolute imports for models
- Updates lint

### CODE REVIEW

**Review by sliptype — APPROVED** [review]
Cool! Why is the models abs path change possible now? Is the plan to use absolute paths for all the directories

**Comment by dylanjeffers** [comment]
> Cool! Why is the models abs path change possible now? Is the plan to use absolute paths for all the directories

I think because we have node module resolve in tsconfig it just works. Basically there were already absolute model imports, so I just kept things consistent!

**Comment by nicoback2** [comment]
ooh thank you so much!  @dylanjeffers  did you run typecheck in web and mobile? curious because when i was using absolute imports, it broke a bunch of things there.

**Comment by dylanjeffers** [comment]
> ooh thank you so much! @dylanjeffers did you run typecheck in web and mobile? curious because when i was using absolute imports, it broke a bunch of things there which is why I changed a bunch to relative.

yeah i didnt.. checking it now though, yeah i think youre right. well at very least ill just keep the /index removal? will try to get to bottom though, cause there are existing absolute model imports there too, so not sure why those work :/

**Pull request merged**
