### PR TITLE
Changes to enable verified referrals on mobile

### PR DESCRIPTION
**Pull request by rickyrombo**
### Description

Initially was identical to #866 but better. Now is just additional exports etc to adopt optimistic challenges in mobile.

- Exports `UserChallengeState` so that it can be imported in mobile
- Moves `profile-progress/store/selectors.js` to `common/store/challenges/selectors.ts`
- Converts `profile-progress` selectors to TypeScript
- Change the check to `_profile_picture_sizes` and `_cover_photo_sizes` in `profile-progress` selector instead of `updatedProfilePicture` and `updatedCoverPhoto` to match `User` type
- Add `_has_reposted` type to computed props to match usage in the app.

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

### How will this change be monitored?

For features that are critical or could fail silently please describe the monitoring/alerting being added.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-ref-v

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-ref-v

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-ref-v

**Comment by rickyrombo** [comment]
This is getting too large - will split out to smaller prs once i have a working build with mobile

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-ref-v

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-ref-v

**Pull request closed without merging**
