### PR TITLE
[AUD-626] Fix demo site & move to cloudflare

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description

Fix demo site (moved to demo.audius.co).

Two things happened here:
1. The lambda@edge on AWS that was previously setting up the demo site has been replaced with a cloudflare worker living at demo.audius.co. That worker just points to the s3 bucket where that content is still hosted.
2. Some large changes to the public site/landing page to resolve routing issues. The crux of those changes were to stop doing window.location.href = <some route> and instead using history.pushState, which allows the re-mounting app router to handle the routing. 

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

Changes to the landing page were large, unfortunately, but thoroughly tested.

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

1. Special build pushed to https://demo.audius.co/build-staging to test
2. All landing page links (desktop & mobile) were tested
3. Demo for this PR should "just work"

### How will this change be monitored?

For features that are critical or could fail silently please describe the monitoring/alerting being added.

Soak on staging for a while

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-aud-626

**Review by jowlee — CHANGES_REQUESTED** [review]
hmm, clicking on the footer from the demo site didn't seem to work - for going to /press, /legal/privacy-policy and /legal/terms-of-use

**Comment by raymondjacobson** [comment]
> hmm, clicking on the footer from the demo site didn't seem to work - for going to /press, /legal/privacy-policy and /legal/terms-of-use

thx. i think this is an issue w the demo site not the landing page bc i can't repro locally. will address this.

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/rj-aud-626

**Comment by raymondjacobson** [comment]
Probers failing b/c missing #683

**Review by jowlee — APPROVED** [review]
LGTM - let's test this on staging a bunch

**Comment by MaleVTuber** [comment]
> hmm, clicking on the footer from the demo site didn't seem to work - for going to /press, /legal/privacy-policy and /legal/terms-of-use

hey can you possibly respond to my issue? I've been waiting for 4 days, and it's pretty urgent.

**Pull request merged**
