### PR TITLE
[PAY-1717] Make sign in/sign up page overlap banner

### PR DESCRIPTION
**Pull request by rickyrombo**
### Description

`position: fixed` is relative to page always, and we don't want scrolling, so this fixes the banner showing up on sign in/sign on.

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

### CODE REVIEW

**Review by dharit-tan — APPROVED** [review]
Does this also make it stick to the top of the page, and is that the desired behavior?

**Comment by rickyrombo** [comment]
> Does this also make it stick to the top of the page, and is that the desired behavior?

Good call, forgot to check small screen sizes - add overflow behavior and fixed the background position

**Review by dharit-tan — APPROVED** [review]

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-sign-on-banner

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/mjp-sign-on-banner

**Pull request merged**
