### PR TITLE
Remove ports for local dev

### PR DESCRIPTION
**Pull request by theoilie**
### Description
Removes ports since they're no longer needed/supported since https://github.com/AudiusProject/audius-protocol/pull/4961 was merged.

### Dragons
None - it's local dev.

### How Has This Been Tested?
Tested signup on client from `npm run web:dev` and `audius-compose up -e 1`. Monitored network tab to ensure the correct endpoints are hit and respond. Note that signup currently doesn't work for an unrelated issue that I'm working on resolving.

### How will this change be monitored?
I'll be using the flow locally.

### Feature Flags ###
N/A

### CODE REVIEW

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/theo-remove-local-ports

**Review by raymondjacobson — APPROVED** [review]
code looks good. i assume it works? 🔥

**Comment by theoilie** [comment]
> code looks good. i assume it works? 🔥

of course! 😎

**Pull request merged**
