### PR TITLE
[C-372 C-376] Add Input component and remove antd input from collection header and filter input

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description
[C-372 C-376] 

* Add new Input component
* Remove antd input from CollectionHeader
* Remove antd input from FilterInput (Used on History Page and Saved Page)

### Dragons

There may be slight size differences

### How Has This Been Tested?

Manually tested, I think I covered all of the current functionality

### How will this change be monitored?

N/A

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Remove-antd-input-component

**Review by sliptype — APPROVED** [review]
Looks awesome! Couple small things I noticed

**Review by sliptype — APPROVED** [review]
Good stuff!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Remove-antd-input-component

**Pull request merged**
