### PR TITLE
Poll identity for cognito existence

### PR DESCRIPTION
**Pull request by sddioulde**
### Description

So that identity has a chance to receive and store flow webhook data

### Dragons

Make sure that current flow is not broken

### How Has This Been Tested?

Updated unit tests and also test manually

### How will this change be monitored?

No monitoring

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-delay-cognito-claim-retry

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-delay-cognito-claim-retry

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-delay-cognito-claim-retry

**Review by piazzatron — APPROVED** [review]

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-delay-cognito-claim-retry

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/sd-delay-cognito-claim-retry

**Pull request merged**
