### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by jowlee**
### Description
Remove the `max_old_space_size` arg from the build command

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

### How will this change be monitored?

For features that are critical or could fail silently please describe the monitoring/alerting being added.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/jowlee-test-fix-ci

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/jowlee-test-fix-ci

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/jowlee-test-fix-ci

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/jowlee-test-fix-ci

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/jowlee-test-fix-ci

**Review by raymondjacobson — APPROVED** [review]
that's cool, how come?

**Comment by jowlee** [comment]
> that's cool, how come?

Honestly not entirely sure - just saw a comment saying to try it - seems to work.  
You can see that I also tried increasing the old_space mem first and that didn't work.

**Pull request merged**
