### PR TITLE
[C-2852 PLAT-1094 PLAT-1093] Add fetch collection by permalink

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Adds feature to fetch collection by permalink. This should not be enabled in prod until a few fixes roll out in the coming weeks.

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-2852-fix-hidden-playlist-slug

**Comment by sabrina-kiam** [comment]
thank you so much dylan!!! i have one question - when i look at https://demo.audius.co/dj-c-2852-fix-hidden-playlist-slug/ray/playlist/a-playlist-testing-slugs-492987202, since i just created this playlist, shouldn't the new slug also work? it leads to a blank page for me https://demo.audius.co/dj-c-2852-fix-hidden-playlist-slug/ray/playlist/a-playlist-testing-slugs

**Review by Kyle-Shanks — APPROVED** [review]
neat

**Comment by sabrina-kiam** [comment]
scenarios i tested:
- created an album via upload
- creating a playlist via left nav
- routing to playlist via search
- routing to playlist from feed
- routing to playlist from profile
- routing to album from profile
- routing to playlist from left nav
- routing to smart collections in explore page
- sharing a playlist

things i want to cover:
- sharing an album
- routing to an album from feed
- routing to playlist/album from notification
- mobile testing
- lmk if there are additional scenarios!

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-2852-fix-hidden-playlist-slug

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-2852-fix-hidden-playlist-slug

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-2852-fix-hidden-playlist-slug

**Pull request merged**
