### PR TITLE
[C-2442] Remove cognito

### PR DESCRIPTION
**Pull request by dylanjeffers**
### Description

Removes cognito from web/mobile

### CODE REVIEW

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Review by sliptype — APPROVED** [review]

**Review by Kyle-Shanks — APPROVED** [review]
Bye Cognito

**Comment by audius-infra** [comment]
It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/dj-c-2442-remove-cognito

**Pull request merged**
