### PR TITLE
Handle twitter & insta oauth profiles better

### PR DESCRIPTION
**Pull request by raymondjacobson**
### Description
Handles oauth profiles from twitter and instagram a bit better. Does a little bit of work to typescriptify + condense the code around processing profiles.

The changes are best understood by the test cases

### Dragons

Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.

For both twitter & instagram (i mocked data since that doesn't work against local):

1. Create an account and oauth with a valid handle that's unclaimed on audius => skips the "edit profile page" of sign up
2. Create an account and oauth with a valid  handle that's claimed on audius => shows the "edit profile page" with handle in use message
3. Create an account and oauth with a handle that's > 16 chars and not verified => truncates => shows the "edit profile page"
4. Create an account and oauth with a handle that's > 16 chars and verified => shows the "edit profile page" with an error text Sorry handle not supported, prompting the user to either leave or change it

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://frontend-demo.audius.co/rj-aud-324

**Review by jowlee — APPROVED** [review]
Thanks for breaking out all the logic in the profile page into the `formatSocialProfile` file.
This all looks good to me. 
Also thx for updating the `validateHandleSucceeded` action to only be for success 🙃 
Question: Is the `skipEdit` variable ever true?

**Review by Kyle-Shanks — APPROVED** [review]

**Comment by raymondjacobson** [comment]
> Thanks for breaking out all the logic in the profile page into the `formatSocialProfile` file.
> This all looks good to me.
> Also thx for updating the `validateHandleSucceeded` action to only be for success 🙃
> Question: Is the `skipEdit` variable ever true?

Yes! It's true on validateHandleSucceeded!

**Comment by raymondjacobson** [comment]
> > Thanks for breaking out all the logic in the profile page into the `formatSocialProfile` file.
> > This all looks good to me.
> > Also thx for updating the `validateHandleSucceeded` action to only be for success 🙃
> > Question: Is the `skipEdit` variable ever true?
> 
> Yes! It's true on validateHandleSucceeded!

!error && !requiresUserReview

requiresUserReview only if the handle > 16 chars

**Pull request merged**
