### PR TITLE
[C-2341] Update tracks table to display tracks marked as deleted as deleted

### PR DESCRIPTION
**Pull request by Kyle-Shanks**
### Description
Update to display marked as deleted tracks the same as deleted tracks in the tracks table

### Dragons

N/A

### How Has This Been Tested?

Manually tested

### How will this change be monitored?

N/A

### Feature Flags ###

N/A

### CODE REVIEW

**Review by dylanjeffers — APPROVED** [review]
Sweet simple enough. So what is marked deleted exactly? Is that an optimistic write datum?

**Review by dylanjeffers — COMMENTED** [review]
And does this issue exist on mobile also?

**Comment by Kyle-Shanks** [comment]
> Sweet simple enough. So what is marked deleted exactly? Is that an optimistic write datum?

yea thats what i looks like. on refresh of the page, is_delete is set so this is just for the optimistic update. and this might exist on mobile? I can check

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/kj-Update-deleted-in-track-table

**Comment by dylanjeffers** [comment]
> > Sweet simple enough. So what is marked deleted exactly? Is that an optimistic write datum?
> 
> yea thats what i looks like. on refresh of the page, is_delete is set so this is just for the optimistic update. and this might exist on mobile? I can check

awesome thanks for context

**Pull request merged**
