### PR TITLE
Website redesign - web and mobile landing page

### PR DESCRIPTION
**Pull request by nicoback2**
### Description
Redesign website to match [spec](https://www.figma.com/file/1C0ySOBAAmj5oR6Fv4pl6I/2022-Landing-Page-Refresh?node-id=698%3A1742)

Remaining TODOs: 
-New downloads page
-New nav banner

[screencapture-localhost-3001-2022-06-21-11_52_48.pdf](https://github.com/AudiusProject/audius-client/files/8950471/screencapture-localhost-3001-2022-06-21-11_52_48.pdf)

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?
Tested in browser in mobile and web viewports

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that a
re critical or could fail silently please describe the monitoring/alerting being added.*

### CODE REVIEW

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--website

**Review by Kyle-Shanks — APPROVED** [review]
Awesome stuff 🔥

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--website

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--website

**Comment by audius-infra** [comment]
Preview this change https://demo.audius.co/nkang--website

**Pull request merged**
